spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vectorsearch
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8181